### PR TITLE
fix bug in string cmp fns (eg string<?); closes #149

### LINKED ISSUE #149: string cmp fns, eg string<? sometimes return wrong result
eg
`(string<? "b" "aa")` should be `#f` but returns `#t`

### PR DESCRIPTION
**Pull request by stchang**

### CODE REVIEW

File: racketscript-compiler/racketscript/compiler/runtime/core/unicode_string.js [hunk 1]
```diff
@@ -434,16 +434,13 @@ export function eq(a, b) {
  * @return {!boolean}
  */
 export function lt(a, b) {
-    if (a.length < b.length) {
-        return true;
-    }
-    const n = a.length;
+    const n = (a.length < b.length) ? a.length : b.length;
```
Comment (glebm) [inline racketscript-compiler/racketscript/compiler/runtime/core/unicode_string.js]: Consider replacing with:

```js
Math.min(a.length, b.length)
```

It is more readable and also an order of magnitude faster in this microbenchmark on Firefox 69: https://jsperf.com/math-min-vs-if-condition-vs/13

Comment (stchang) [reply racketscript-compiler/racketscript/compiler/runtime/core/unicode_string.js]: Thanks, I'll fix it
